[package]
name = "rs-tokeniser"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
fst = "0.4.7"
rand = "0.8.5"
rayon = "1.10.0"
regex = "1.10.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
